name: "Deploy NextJS VPS Hostinger"
on:
  push:
    branches:
      - main

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Executar git pull no servidor
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /projects
            echo "PWD inicial:"
            pwd
            echo "Conteúdo de /projects:"
            ls -la /root/projects

            if [ ! -d "/root/projects/deploy-vps-nextjs/.git" ]; then
                echo "Clonando repositório..."
                git clone https://github.com/jnerydesigner/deploy-vps-nextjs /root/projects/deploy-vps-nextjs
            else
                echo "Repositório já clonado"
            fi

            echo "Entrando na pasta do projeto"
            cd /root/projects/deploy-vps-nextjs
            echo "PWD após cd:"
            pwd
            echo "Conteúdo da pasta do projeto:"
            ls -la

            echo "Executando git pull"
            git pull origin main

      - name: Executar o Build No Servidor
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            /root/projects/deploy-vps-nextjs
            npm run build
